# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0002_animalrescatado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animalRescatado',
            new_name='registro_mascota',
        ),
    ]
