# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misperris', '0004_auto_20181104_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('correo_electronico', models.CharField(max_length=200, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=200, verbose_name='Contrase\xf1a')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
