# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0008_auto_20181105_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrousuario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='registromascota',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registromascota',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='registromascota',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='registroUsuario',
        ),
    ]
