# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 05:06
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0010_auto_20181107_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromascota',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
