# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 17:40
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misperris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animalRescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('raza_predominante', models.TextField(verbose_name='Raza predominante')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
