# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0006_registromascota_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
