# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0007_auto_20181105_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromascota',
            name='estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrousuario',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Publicacion'),
        ),
    ]
