# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 03:52
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0009_auto_20181106_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromascota',
            name='estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registromascota',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Publicacion'),
        ),
        migrations.AddField(
            model_name='registromascota',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
